import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Map;

import labos.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'a' at '15/12/16 19:33' with Gradle 3.2.1
 *
 * @author a, @date 15/12/16 19:33
 */

public class LibraryTest {

    @Test public void testSomeLibraryMethod() {
        //Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());

        Lab lab = Main.getLab("1");
        Map<String, Map<Integer, String>> h = lab.getHoursInfo();
        System.out.println(h.get("lunes").get(9));

        //Logger logger = LoggerFactory.getLogger("logger");
        //logger.error(h.get("lunes").get(9));
    }

}
