import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'a' at '15/12/16 19:33' with Gradle 3.2.1
 *
 * @author a, @date 15/12/16 19:33
 */

public class LibraryTest {
/*
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
*/
}
